AWSTemplateFormatVersion: 2010-09-09
Description: Deploys an EFS file system with the appropriate folder mounts required for Prestashop ECS Containers.
Parameters:
  StackUUID:
    Description: Stack UUID
    Type: String
  VPCId:
    Description: The ID of the VPC that this stack is deployed in
    Type: String
  PrivateSubnetOne:
    Description: Private subnet 1 that the EFS will be deployed in.
    Type: String
  PrivateSubnetTwo:
    Description: Private subnet 2 that the EFS will be deployed in.
    Type: String
Resources:
  # Security Group for controlling access to the EFS
  EFSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group to control access to the EFS
      VpcId: !Ref 'VPCId'
  # img folder EFS setup
  ImgEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: Img
      PerformanceMode: generalPurpose
  ImgMountTargetAZ1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'ImgEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetOne'
  ImgMountTargetAZ2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'ImgEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetTwo'

  # modules folder EFS setup
  ModulesEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: Modules
      PerformanceMode: generalPurpose
  ModulesMountTargetAZ1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'ModulesEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetOne'
  ModulesMountTargetAZ2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'ModulesEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetTwo'

  # override folder EFS setup
  OverrideEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: Override
      PerformanceMode: generalPurpose
  OverrideMountTargetAZ1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'OverrideEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetOne'
  OverrideMountTargetAZ2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'OverrideEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetTwo'
  # cache folder EFS setup
  CacheEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: Cache
      PerformanceMode: generalPurpose
  CacheMountTargetAZ1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'CacheEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetOne'
  CacheMountTargetAZ2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'CacheEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetTwo'

  # theme folder EFS setup
  ThemeEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: Theme
      PerformanceMode: generalPurpose
  ThemeMountTargetAZ1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'ThemeEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetOne'
  ThemeMountTargetAZ2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'ThemeEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetTwo'

  # config folder EFS setup
  ConfigEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: Config
      PerformanceMode: generalPurpose
  ConfigMountTargetAZ1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'ConfigEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetOne'
  ConfigMountTargetAZ2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref 'ConfigEFS'
      SecurityGroups:
        - !Ref 'EFSSG'
      SubnetId: !Ref 'PrivateSubnetTwo'

  #-----------------------------------------------------------
  # The following resources are used to conduct periodic backups
  # for the EFS file systems.
  #-----------------------------------------------------------
  FileSystemBackupVault:
    Type: AWS::Backup::BackupVault
    DeletionPolicy: Retain
    Properties:
      BackupVaultName: !Sub
        - ${StackUUID}-EFSBackupVault
        - { StackUUID: !Ref 'StackUUID' }
      AccessPolicy: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Deny",
              "Principal": "*",
              "Action": "backup:DeleteBackupVault",
              "Resource": "*"
            }
          ]
        }

  FileSystemBackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: Daily-Weekly-Monthly
        BackupPlanRule:
          - RuleName: DailyBackups
            TargetBackupVault: !Ref 'FileSystemBackupVault'
            ScheduleExpression: "cron(0 5 ? * * *)"
            StartWindowMinutes: 480
            CompletionWindowMinutes: 10080
            Lifecycle:
              DeleteAfterDays: 35
          - RuleName: MonthlyBackups
            TargetBackupVault: !Ref 'FileSystemBackupVault'
            ScheduleExpression: "cron(0 5 1 * ? *)"
            StartWindowMinutes: 480
            CompletionWindowMinutes: 10080
            Lifecycle:
              DeleteAfterDays: 35

  #-----------------------------------------------------------
  # File system backup selection
  #-----------------------------------------------------------
  FileSystemBackupSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !Ref 'FileSystemBackupPlan'
      BackupSelection:
        IamRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/AWSBackupDefaultServiceRole
        Resources:
          - !Sub arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${ImgEFS}
          - !Sub arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${ThemeEFS}
          - !Sub arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${CacheEFS}
          - !Sub arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${ConfigEFS}
          - !Sub arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${OverrideEFS}
          - !Sub arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${ModulesEFS}
        SelectionName: !Sub "${AWS::StackName}-backup"

Outputs:
  EFSSG:
    Description: EFS Security Group
    Value: !Ref 'EFSSG'
    Export:  
      Name: !Sub
        - ${StackUUID}:EFSSG
        - { StackUUID: !Ref 'StackUUID' }
  ConfigEFS:
    Description: Config EFS
    Value: !Ref 'ConfigEFS'
    Export: 
      Name:  !Sub
        - ${StackUUID}:ConfigEFS
        - { StackUUID: !Ref 'StackUUID' }
  ThemeEFS:
    Description: Theme EFS
    Value: !Ref 'ThemeEFS'
    Export: 
      Name:  !Sub
        - ${StackUUID}:ThemeEFS
        - { StackUUID: !Ref 'StackUUID' }
  ModulesEFS:
    Description: Modules EFS
    Value: !Ref 'ModulesEFS'
    Export: 
      Name: !Sub
        - ${StackUUID}:ModulesEFS
        - { StackUUID: !Ref 'StackUUID' }
  OverrideEFS:
    Description: Override EFS
    Value: !Ref 'OverrideEFS'
    Export: 
      Name:  !Sub
        - ${StackUUID}:OverrideEFS
        - { StackUUID: !Ref 'StackUUID' }
  CacheEFS:
    Description: Cache EFS
    Value: !Ref 'CacheEFS'
    Export: 
      Name:  !Sub
        - ${StackUUID}:CacheEFS
        - { StackUUID: !Ref 'StackUUID' }
  ImgEFS:
    Description: Img EFS
    Value: !Ref 'ImgEFS'
    Export: 
      Name: !Sub
        - ${StackUUID}:ImgEFS
        - { StackUUID: !Ref 'StackUUID' }
