AWSTemplateFormatVersion: '2010-09-09'
Description: Configures autoscaling between the EC2 ASG and ECS Service using CloudWatch alarms.
Parameters:
  AutoscalingRoleARN:
    Description: EC2 Autoscaling Role arn.
    Type: String
  AutoScalingGroup:
    Description: Name of EC2 AutoScaling Group.
    Type: String
  ServiceName:
    Description: Name of the ECS Service.
    Type: String
  Cluster:
    Description: Name of the ECS Cluster.
    Type: String
  LowCPUThreshold:
    Type: Number
    Default: 30
  HighCPUThreshold:
    Type: Number
    Default: 60
  LowMemThreshold:
    Type: Number
    Default: 30
  HighMemThreshold:
    Type: Number
    Default: 60

Resources:
  # Enables Autoscaling for the ECS service. A 1:1 ratio is maintained between ECS tasks and EC2 instances.
  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      ServiceNamespace: 'ecs'
      ScalableDimension: 'ecs:service:DesiredCount'
      ResourceId:
        Fn::Join:
          - '/'
          - - service
            - !Ref 'Cluster'
            - !Ref 'ServiceName'
      MinCapacity: 1
      MaxCapacity: 100
      RoleARN: !Ref 'AutoscalingRoleARN'

  ScaleServiceUpPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: ScalableTarget
    Properties:
      PolicyName: !Join
        - '-'
        - - !Ref 'ServiceName'
          - ScaleServiceUpPolicy
      PolicyType: StepScaling
      ResourceId:
        Fn::Join:
          - '/'
          - - service
            - !Ref 'Cluster'
            - !Ref 'ServiceName'
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: 'ecs'
      StepScalingPolicyConfiguration:
        AdjustmentType: 'ChangeInCapacity'
        StepAdjustments:
          - ScalingAdjustment: 1
            MetricIntervalLowerBound: 0
        MetricAggregationType: 'Average'
        Cooldown: 180

  ScaleASGUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: "ChangeInCapacity"
      PolicyType: "SimpleScaling"
      AutoScalingGroupName:
        !Ref 'AutoScalingGroup'
      ScalingAdjustment: 1

  HighCpuUsageAlarm:
    DependsOn:
      - ScalableTarget
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Join
        - '-'
        -  - !Ref 'ServiceName'
           - HighCpuAlarm

      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value:
            !Ref 'ServiceName'
        - Name: ClusterName
          Value:
            !Ref 'Cluster'
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: !Ref 'HighCPUThreshold'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref 'ScaleServiceUpPolicy'
        - !Ref 'ScaleASGUpPolicy'

  HighMemUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn:
      - ScalableTarget
    Properties:
      AlarmName: !Join
        - '-'
        - - !Sub "${AWS::StackName}:ServiceName"
          - 'HighMemAlarm'
      MetricName: MemUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value:
            !Ref 'ServiceName'
        - Name: ClusterName
          Value:
            !Ref 'Cluster'
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: !Ref 'HighMemThreshold'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref 'ScaleServiceUpPolicy'
        - !Ref 'ScaleASGUpPolicy'

  ScaleServiceDownPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: ScalableTarget
    Properties:
      PolicyName: !Join
        - '-'
        - - !Ref 'ServiceName'
          - 'ScaleServiceDownPolicy'
      PolicyType: StepScaling
      ResourceId:
        Fn::Join:
          - '/'
          - - service
            - !Ref 'Cluster'
            - !Ref 'ServiceName'
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: 'ecs'
      StepScalingPolicyConfiguration:
        AdjustmentType: 'ChangeInCapacity'
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -1
        MetricAggregationType: 'Average'
        Cooldown: 180

  ScaleASGDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: "ChangeInCapacity"
      PolicyType: "SimpleScaling"
      AutoScalingGroupName:
        !Ref 'AutoScalingGroup'
      ScalingAdjustment: -1

  LowCpuUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn:
      - ScalableTarget
      - ScaleServiceUpPolicy
      - ScaleASGUpPolicy
    Properties:
      AlarmName: !Join
        - '-'
        - - !Ref 'ServiceName'
          - 'LowCpuAlarm'
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value:
            !Ref 'ServiceName'
        - Name: ClusterName
          Value:
            !Ref 'Cluster'
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: !Ref 'LowCPUThreshold'
      ComparisonOperator: LessThanOrEqualToThreshold
      AlarmActions:
        - !Ref 'ScaleServiceDownPolicy'
        - !Ref 'ScaleASGDownPolicy'

  LowMemUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn:
      - ScalableTarget
      - ScaleServiceUpPolicy
      - ScaleASGUpPolicy
    Properties:
      AlarmName: !Join
        - '-'
        - - !Ref 'ServiceName'
          - 'LowMemAlarm'
      MetricName: MemUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value:
            !Ref 'ServiceName'
        - Name: ClusterName
          Value:
            !Ref 'Cluster'
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: !Ref 'LowMemThreshold'
      ComparisonOperator: LessThanOrEqualToThreshold
      AlarmActions:
        - !Ref 'ScaleServiceDownPolicy'
        - !Ref 'ScaleASGDownPolicy'
